#ifndef PIKA_RESOURCES_HPP
#define PIKA_RESOURCES_HPP

#include "embed/resource_holder.hpp"  // generated by embed

namespace pika {

// Game assets
static constexpr char sprite_sheet_filename [] = "assets/images/sprite_sheet_new.png";
static constexpr char music_background_filename [] = "assets/sounds/bgm.mp3";
static constexpr char sound_pi_filename [] = "assets/sounds/pi.wav";
static constexpr char sound_pika_filename [] = "assets/sounds/pika.wav";
static constexpr char sound_chu_filename [] = "assets/sounds/chu.wav";
static constexpr char sound_pikachu_filename [] = "assets/sounds/pikachu.wav";
static constexpr char sound_pipikachu_filename [] = "assets/sounds/pipikachu.wav";
static constexpr char sound_ball_hit_filename [] = "assets/sounds/ball_hit.wav";
static constexpr char sound_ball_ground_filename [] = "assets/sounds/ball_ground.wav";
static constexpr char text_font_filename [] = "assets/font.ttf";

static constexpr unsigned int text_font_size = 45;

/**
 * Load a game resource. First try to load it from the binary embedded data.
 * If that fails, load it from disk.
 * If the resource cannot be loaded, an exception is thrown.
 *
 * NOTE: After usage, it is required to manually call SDL_CloseIO to free the memory.
 *   This is usually handled by SDL_LoadPNG(..., bool close_io) and similar functions.
 * @param filename The resource filename (relative to the project root)
 * @return A (owning) pointer to a SDL_IOStream
 */
inline SDL_IOStream* load_resource(const char* filename) {
  SDL_IOStream* resource_data = nullptr;
  try {
    const ResourceHolder rh;
    const auto sprite_sheet_res = rh(filename);
    SDL_Log("Resource %s size = %zu bytes", filename, sprite_sheet_res.size());
    resource_data = SDL_IOFromConstMem(sprite_sheet_res.data(), sprite_sheet_res.size());
  } catch (const std::runtime_error& e) {
    SDL_Log("Failed to load embedded resource: %s", e.what());
    SDL_Log("Loading resource %s from file", filename);
    resource_data = SDL_IOFromFile(filename, "r");
  }

  if (resource_data == nullptr) {
    SDL_Log( "Unable to load resource %s! SDL Error: %s\n", filename, SDL_GetError());
    throw std::runtime_error("Failed to load resource!");
  }

  return resource_data;
}

} // namespace pika

#endif // PIKA_RESOURCES_HPP
